apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
  labels:
    name: usermgmt-webapp
spec:
  type: LoadBalancer
  selector:
    app: app-usermgmt-webapp
  ports:
  - port: 80
    targetPort: 8080
